### Категорийные данные [Домашнее задание]

**Примечание:**

> Пожалуйста, не удаляйте комментарии или строки кода.

1. Пожалуйста, импортируйте необходимые библиотеки, и загрузите набор данных ```"titanic"``` из библиотеки ```seaborn```.

In [4]:
# Начало кода
import seaborn as sns
import pandas as pd
import numpy as np

titanic = sns.load_dataset("titanic")
data=titanic.copy()
titanic.head()
# Конец кода

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

2. Пожалуйста, реализуйте функцию ```label_encoding(labels)```, которая будет возвращать закодированные категорийные данные на основе ```Label Encoding```. Вы не можете использовать библиотеку ```sklearn``` в этой задаче.

In [11]:
def label_encoding(labels):
    # Начало кода
    label2idx = {}
    idx2label = {}
    encoded = []
    
    uniques = np.unique(labels)[::-1]
    for i in range(len(uniques)):
        label2idx[uniques[i]] = i
        idx2label[i] = uniques[i]
    for i in labels:
        encoded.append(label2idx[i])
    # Конец кода
    return (encoded, label2idx, idx2label)

encoded, label2idx, idx2label = label_encoding(data["sex"].values)
print(encoded[:10])
print(label2idx)
print(idx2label)

[0, 1, 1, 1, 0, 0, 0, 0, 1, 1]
{'male': 0, 'female': 1}
{0: 'male', 1: 'female'}


### Ожидаемые результаты:

```python
[0, 1, 1, 1, 0, 0, 0, 0, 1, 1]
{'male': 0, 'female': 1}
{0: 'male', 1: 'female'}
```

3. Пожалуйста, реализуйте функцию ```onehot_encoding(labels)```, которая будет возвращать закодированные категорийные данные на основе ```One-hot Encoding```. Вы не можете использовать библиотеку ```sklearn``` в этой задаче.

In [24]:
def onehot_encoding(labels):
    # Начало кода
    label2idx = {}
    idx2label = {}
    encodings = []
    
    uniques = np.unique(labels)[::-1]
    for i in range(len(uniques)):
        label2idx[uniques[i]] = i
        idx2label[i] = uniques[i]
    uniques_idx = np.array([label2idx[i] for i in uniques])
    for i in labels:
        arr = label2idx[i] == uniques_idx
        arr = arr.astype(float)
        encodings.append(arr)
    encodings = np.array(encodings)
    # Конец кода
    return (encodings, label2idx, idx2label)

encodings, label2idx, idx2label = onehot_encoding(data["sex"].values)
print(encodings)
print(label2idx)
print(idx2label)

[[1. 0.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [1. 0.]
 [1. 0.]]
{'male': 0, 'female': 1}
{0: 'male', 1: 'female'}


### Ожидаемые результаты:

```python
[[1. 0.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [1. 0.]
 [1. 0.]]
{'male': 0, 'female': 1}
{0: 'male', 1: 'female'}
```

4. Пожалуйста, реализуйте функцию ```label_encoding_sklearn(labels)```, которая будет возвращать закодированные категорийные данные на основе ```Label Encoding```. Вы должны использовать библиотеку ```sklearn``` в этой задаче.

In [28]:
from sklearn.preprocessing import LabelEncoder

def label_encoding_sklearn(labels):
    # Начало кода
    encoded = []
    
    encoder = LabelEncoder()
    encoded = encoder.fit_transform(np.array(labels))
    # Конец кода
    return (encoded, encoder)

encoded, encoder = label_encoding_sklearn(data["sex"].values.reshape(-1,1))
print(encoded[:10])
print(encoder)

[1 0 0 0 1 1 1 1 0 0]
LabelEncoder()


### Ожидаемые результаты:

```python
[1 0 0 0 1 1 1 1 0 0]
LabelEncoder()
```

5. Пожалуйста, реализуйте функцию ```onehot_encoding_sklearn(labels)```, которая будет возвращать закодированные категорийные данные на основе ```One-hot Encoding```. Вы должны использовать библиотеку ```sklearn``` в этой задаче.

In [30]:
from sklearn.preprocessing import OneHotEncoder

def onehot_encoding_sklearn(labels):
    # Начало кода
    encoded = []
    
    encoder = OneHotEncoder()
    encoded = encoder.fit_transform(np.array(labels)).toarray()
    # Конец кода
    return (encoded, encoder)
encoded, encoder = onehot_encoding_sklearn(data["sex"].values.reshape(-1,1))
print(encoded)
print(encoder)

[[0. 1.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [0. 1.]
 [0. 1.]]
OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)


### Ожидаемые результаты:

```python
[[0. 1.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [0. 1.]
 [0. 1.]]
OneHotEncoder()
```

6. Пожалуйста, реализуйте функцию ```hash_encoding_sklearn(labels)```, которая будет возвращать закодированные категорийные данные на основе ```Hashing```. Вы должны использовать библиотеку ```sklearn``` в этой задаче.

In [32]:
from sklearn.feature_extraction import FeatureHasher

def hash_encoding_sklearn(labels, n_features=4, input_type="string"):
    # Начало кода
    encoded = []
    encoder = FeatureHasher(n_features = n_features, input_type = input_type)
    encoded = encoder.fit_transform(np.array(labels)).toarray()
    # Конец кода
    return (encoded, encoder)
encoded, encoder = hash_encoding_sklearn(data["sex"].values.reshape(-1,1))
print(encoded)
print(encoder)

[[-1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0. -1.  0.  0.]
 ...
 [ 0. -1.  0.  0.]
 [-1.  0.  0.  0.]
 [-1.  0.  0.  0.]]
FeatureHasher(alternate_sign=True, dtype=<class 'numpy.float64'>,
              input_type='string', n_features=4)


### Ожидаемые результаты:

```python
[[-1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0. -1.  0.  0.]
 ...
 [ 0. -1.  0.  0.]
 [-1.  0.  0.  0.]
 [-1.  0.  0.  0.]]
FeatureHasher(input_type='string', n_features=4)
```

7. Теперь попробуйте использовать эти реализованные функции и преобразовать другие категориальные столбцы в ```data``` в закодированные данные.

In [34]:
data["embarked"].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [36]:
# Начало кода
encoded, encoder = label_encoding_sklearn(data["embarked"].dropna().values.reshape(-1,1))
print(encoded[:10])
print(encoder)
# Конец кода

[2 0 2 2 2 1 2 2 2 0]
LabelEncoder()


In [38]:
data["class"].unique()

[Third, First, Second]
Categories (3, object): [Third, First, Second]

In [41]:
encoded, encoder = onehot_encoding_sklearn(data["class"].astype("object").values.reshape(-1,1))
print(encoded[:10])
print(encoder)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]]
OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)


In [42]:
data["who"].unique()

array(['man', 'woman', 'child'], dtype=object)

In [59]:
encoded, encoder = hash_encoding_sklearn(data["who"].values.reshape(-1,1),n_features=4)
print(encoded[5:15])
print(encoder)

[[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]]
FeatureHasher(alternate_sign=True, dtype=<class 'numpy.float64'>,
              input_type='string', n_features=4)


In [60]:
data["adult_male"].unique()

array([ True, False])

In [62]:
encoded, label2idx, idx2label = label_encoding(data["adult_male"].values)
print(encoded[:10])

[0, 1, 1, 1, 0, 0, 0, 1, 1, 1]


In [63]:
data["embark_town"].unique()

array(['Southampton', 'Cherbourg', 'Queenstown', nan], dtype=object)

In [65]:
encodings, label2idx, idx2label = onehot_encoding(data["embark_town"].dropna().values)
print(encodings)

[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


### Отличная работа