### Метрики регрессии [Домашнее задание]

**Примечание:**

> Пожалуйста, не удаляйте комментарии или строки кода.

1. Пожалуйста, импортируйте необходимые библиотеки:

```python
numpy
sklearn
```

In [4]:
# Начало кода
import numpy as np
import sklearn
# Конец кода

2. Создайте два ```np.ndarray``` массива ```targets```, ```predictions``` формы ```(100,)``` каждый, с целыми числами от 50000 до 100000. Сначала сгенерируйте массив ```targets```, а затем ```predictions```. (Установите ```np.random.seed``` на 1)

In [5]:
# Начало кода
np.random.seed(1)

targets = np.random.randint(50000,100001,(100,))
predictions = np.random.randint(50000,100001,(100,))
# Конец кода
print(targets[:10])
print(predictions[:10])

[83003 62172 55192 82511 93723 57813 71440 82912 70609 99100]
[92755 99144 83229 79236 54059 80869 83483 72791 56221 85528]


### Ожидаемые результаты:

```python
[83003 62172 55192 82511 93723 57813 71440 82912 70609 99100]
[92755 99144 83229 79236 54059 80869 83483 72791 56221 85528]
```

3. Пожалуйста, реализуйте функцию ```calc_mse(truth, preds)```, которая будет возвращать MSE, рассчитанную с использованием ```truth``` и ```preds```. Вы не можете использовать библиотеку ```sklearn``` в этой задаче.

In [6]:
# Начало кода
def calc_mse(truth,preds):
    mse = np.square(truth-preds).mean()
    return mse    
# Конец кода
print(calc_mse(targets,predictions))

368636309.49


### Ожидаемые результаты:

```python
411585982.45
```

4. Пожалуйста, реализуйте функцию ```calc_rmse(truth, preds)```, которая будет возвращать RMSE, рассчитанную с использованием ```truth``` и ```preds```. Вы не можете использовать библиотеку ```sklearn``` в этой задаче.

In [8]:
# Начало кода
def calc_rmse(truth,preds):
    rmse = (np.square(truth-preds).mean())**(1/2)
    return rmse
# Конец кода
print(calc_rmse(targets,predictions))

19199.903892728213


### Ожидаемые результаты:

```python
20287.581976420945
```

5. Пожалуйста, реализуйте функцию ```calc_mae(truth, preds)```, которая будет возвращать MAE, рассчитанную с использованием ```truth``` и ```preds```. Вы не можете использовать библиотеку ```sklearn``` в этой задаче.

In [9]:
# Начало кода
def calc_mae(truth,preds):
    mae = (abs(truth-preds).mean())
    return mae
# Конец кода
print(calc_mae(targets,predictions))

16559.79


### Ожидаемые результаты:

```python
16559.79
```

6. Пожалуйста, реализуйте функцию ```calc_r2(truth, preds)```, которая будет возвращать $R^2$, рассчитанную с использованием ```truth``` и ```preds```. Вы не можете использовать библиотеку ```sklearn``` в этой задаче.

In [15]:
# Начало кода
def calc_r2(truth,preds):
    r2 = 1 - calc_mse(truth,preds)/calc_mse(truth,truth.mean())
    return r2
# Конец кода
print(calc_r2(targets,predictions))

-0.7808925406279765


### Ожидаемые результаты:

```python
-0.9883836374835617
```

7. Пожалуйста, реализуйте функцию ```calc_adjusted_r2(truth, preds, k=1)```, которая будет возвращать $Adjusted R^2$, рассчитанную с использованием ```truth``` и ```preds``` (```k``` - количество параметров модели). Вы не можете использовать библиотеку ```sklearn``` в этой задаче.

In [16]:
# Начало кода
def calc_adjusted_r2(truth,preds,k=1):
    n = len(truth)
    adj_r2 = 1 - (n - 1)*(1-calc_r2(truth,preds))/(n-k-1)
    return adj_r2
# Конец кода
print(calc_adjusted_r2(targets,predictions))

-0.7990649134915275


### Ожидаемые результаты:

```python
-1.0086732664374756
```

8. Теперь сравните результаты всех реализованных функций выше с результатами, сгенерированными соответствующими функциями из ```sklearn.metrics```.

In [22]:
# Начало кода
import sklearn.metrics as metrics

print(f"MSE custom: {calc_mse(targets,predictions)}, MSE sklearn.metrics: {metrics.mean_squared_error(targets,predictions)}")
print(f"RMSE custom: {calc_rmse(targets,predictions)}, RMSE sklearn.metrics: {metrics.mean_squared_error(targets,predictions,squared = False)}")
print(f"MAE custom: {calc_mae(targets,predictions)}, MAE sklearn.metrics: {metrics.mean_absolute_error(targets,predictions)}")
print(f"R2 custom: {calc_r2(targets,predictions)}, R2 sklearn.metrics: {metrics.r2_score(targets,predictions)}")

# Конец кода

MSE custom: 368636309.49, MSE sklearn.metrics: 368636309.49
RMSE custom: 19199.903892728213, RMSE sklearn.metrics: 19199.903892728213
MAE custom: 16559.79, MAE sklearn.metrics: 16559.79
R2 custom: -0.7808925406279765, R2 sklearn.metrics: -0.7808925406279763


### Отличная работа